### ISSUE TITLE
How to load the checkpoints?

### ISSUE THREAD

**Issue by QuintessaQ** [tengteng95/Pose-Transfer#11]
I want to load the checkpoints saved in the ./checkpoints directory. Is there any way I can load them instead of restarting a new training everytime?

**Comment by tengteng95** [comment]
Hi, for continuing training, you can add **--continue_train --which_epoch epoch_number --epoch_count epoch_number+1** at the end of the training script. For example, if you want to train from the 300th epoch, just use **--continue_train --which_epoch 300 --epoch_count 301**.

**Comment by QuintessaQ** [comment]
I see. Thank you so much!
