### ISSUE TITLE
Compatibility problem of pretrained model.

### ISSUE THREAD

**Issue by luowy1001** [tengteng95/Pose-Transfer#12]
Hi @tengteng95, thanks for your great work!
There is a compatibility problem when I want to load the pretrained model for testing:
```
RuntimeError: Error(s) in loading state_dict for PATNetwork:
        Unexpected running stats buffer(s) "model.stream1_down.2.running_mean" and "model.stream1_down.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
```
Can you give me some suggestions to solve this problem?
In addition, how to determine whether the training is completed or not, and how many epochs need?
THANKS!

**Comment by tengteng95** [comment]
Hi, I guess the problem is the unmatched pytorch version. In pytorch 1.0, running_mean and running_var are not saved for the Instance Normalization layer by default. Hence, you should first launch **python tool/rm_insnorm_running_vars.py** to remove corresponding keys in the pretrained model.

**Comment by luowy1001** [comment]
solved, thanks for your reply!
