### ISSUE TITLE
What do "BP" and "P" stand for in the program?

### ISSUE THREAD

**Issue by QuintessaQ** [tengteng95/Pose-Transfer#13]
Greetings! When we are training the model with market-1501 dataset, we have P_input_nc==3 and BP_input_nc === 18. I assume P_input_nc is the number of channels for input images, while BP_input_nc is the number of channels for input poses, aka the 18-keypoint representation. In this case, what do "BP" and "P" stand for respectively? Thanks in advance!

**Comment by tengteng95** [comment]
Hi, you're right. "P" stands for "Person", and "BP" stands for 'Bone for Person'.

**Comment by QuintessaQ** [comment]
Oh I see. Thanks a lot!

**Comment by 2110317008** [comment]
> Greetings! When we are training the model with market-1501 dataset, we have P_input_nc==3 and BP_input_nc === 18. I assume P_input_nc is the number of channels for input images, while BP_input_nc is the number of channels for input poses, aka the 18-keypoint representation. In this case, what do "BP" and "P" stand for respectively? Thanks in advance!

I would like to ask what does D_PP and D_PB mean in the code? In addition, our input is Pc, St and Sc. What are the meanings of input_P1_set, input_BP1_set, input_P2_set and input_BP2_set in the code?

**Comment by QuintessaQ** [comment]
D_PP is the appearance discriminator as mentioned in the paper, aka the discriminator that checks whether the generated image and the conditional image are the same person or not. D_PB is the shape discriminator, and it checks whether the pose of the generated image matches the target pose. Input_P1 and input_P2 is an image pair of the same person, or the conditional image and the target image. BP simply means the bone/pose/keypoints of that person image.

**Comment by L-WWEEII** [comment]
> D_PP is the appearance discriminator as mentioned in the paper, aka the discriminator that checks whether the generated image and the conditional image are the same person or not. D_PB is the shape discriminator, and it checks whether the pose of the generated image matches the target pose. Input_P1 and input_P2 is an image pair of the same person, or the conditional image and the target image. BP simply means the bone/pose/keypoints of that person image.

you are right! cool!
