### ISSUE TITLE
DeepFashion dataset not found?

### ISSUE THREAD

**Issue by jiyooonp** [tengteng95/Pose-Transfer#137]
Hello, 
I am not sure where the train/test dataset is supposed to be downloaded. It doesn't seem to be on the drive link. 
Also, the fasion-resize-pairs-train.csv, fasion-resize-pairs-test.csv, fasion-resize-annotation-train.csv, fasion-resize-annotation-train.csv files are not downloadable. Can anyone help me with this? 
Thank you!

**Comment by c1043875898** [comment]
Hello, is the problem solved？
