### ISSUE TITLE
How to use the pre-trained model ‘latest_net_netG.pth’

### ISSUE THREAD

**Issue by plasticMeltryllis** [tengteng95/Pose-Transfer#14]
Nice work.I downloaded your trained model latest_net_netG.pth, but I don't know how to use it. I am new to github. I could only load some paramters from latest_net_netG.pth. Could you tell me which I should do to use the .pth file?

**Comment by zrhyst23** [comment]
> Nice work.I downloaded your trained model latest_net_netG.pth, but I don't know how to use it. I am new to github. I could only load some paramters from latest_net_netG.pth. Could you tell me which I should do to use the .pth file?

i don't understand either.Have you soveld now？i want to use the pre-trained model to test，but i failed to load the model.How to set?

**Comment by amanshenoy** [comment]
> > Nice work.I downloaded your trained model latest_net_netG.pth, but I don't know how to use it. I am new to github. I could only load some paramters from latest_net_netG.pth. Could you tell me which I should do to use the .pth file?
> 
> i don't understand either.Have you soveld now？i want to use the pre-trained model to test，but i failed to load the model.How to set?

All three .pth files would go into `./Pose-Transfer/checkpoints/`
