### ISSUE TITLE
Keypoint_y and keypoint_x in market-annotation-train.csv

### ISSUE THREAD

**Issue by QuintessaQ** [tengteng95/Pose-Transfer#16]
Greetings! I'm wondering what keypoint_y and keypoint_x stand for in market-annotation-train.csv. I suppose they represent the y and x coordinates of those 18 keypoints? Also, to generate keypoints files by ourselves, are we supposed to change the path input_folder in tool/compute_coordinates.py to a directory that contains all our training images? Thanks in advance!

**Comment by budui** [comment]
1. yes. `[y1, y2, ..., y18]: [x1, x2, ..., x18]` stand for 18 keypoints `(x1, y1),(x2, y2),...,(x18, y18)`

2. yes. Tips: use `jpg`(3 channels, RGB) images rather than `png` images (4 channels, RGBA).

**Comment by QuintessaQ** [comment]
Thanks!
