### ISSUE TITLE
how many training data in Market1501 did you use to train your model? 

### ISSUE THREAD

**Issue by lulujianjie** [tengteng95/Pose-Transfer#17]
Hi, This is nice work!
I am working on reproducing it but always get worse results than yours. The following test result are generated by the model trained for 50 epochs and 100 epochs. 
![0-50](https://user-images.githubusercontent.com/9878804/59499248-958b0f00-8ec9-11e9-855a-2abb292a5071.jpg)
![0-100](https://user-images.githubusercontent.com/9878804/59499261-9d4ab380-8ec9-11e9-99d4-ed3b6b9cc756.jpg)

I have noticed that you mentioned results would be good after 500 epochs in another issue.

Since if I use all data described in the training.csv for 500 epochs on RTX 2080 12G, it would take about 600+ hours with batchsize 32.
So could you tell me how many training data in Market1501 did you use to train your model?
And as you can see the results look a little blurry, can you give me any suggestion?

**Comment by budui** [comment]
It seems like that every epoch have only 4000 pairs in the author's implementation,
which means 4000*500/260000=7.69 epoch ?

**Comment by tengteng95** [comment]
@budui Yes, you're right. Thanks for your reply. @lulujianjie  You can check the file **data/keypoint.py** (line94) for details. It won't take a long time for training on the Market-1501 dataset. According to my experience, it takes around 20 ~30 hours for finishing the training. You can also use multiple GPUs for faster training.

**Comment by lulujianjie** [comment]
Thanks for your kind reply. I noticed that you set a random index for data_loader, which means every epoch could include different samples. Nice implementation!

**Comment by Meimeiainaonao** [comment]
> 260000

Hi ，what  does the 260000 mean?
