### ISSUE TITLE
about pose transfer quality

### ISSUE THREAD

**Issue by maliho0803** [tengteng95/Pose-Transfer#18]
you using paired samples for training, maybe it will get worse results when I give a specified pose that not appeared in one ids?

**Comment by tengteng95** [comment]
Hi, it works well with various poses since the appearances and poses are independent. You refer to Fig.1 in our paper and Fig.6~8 in the supplementary, which illustrate the generated images with randomly sampled poses from the whole test dataset.

**Comment by maliho0803** [comment]
Thank you very much for your reply! I will try it. One more question, the quality of the generated image have some relationship with the resolution of original picture? Such as the original picture is smaller than the input of the model?

**Comment by tengteng95** [comment]
I think it will be okay if the resolution is similar when training and testing. However, a large difference in resolution may lead to unsatisfying results.
