### ISSUE TITLE
How did you processed the Fashion Dataset?

### ISSUE THREAD

**Issue by Lotayou** [tengteng95/Pose-Transfer#19]
Thanks for you amazing work! I noticed that in your pose-heatmap generation script [here](https://github.com/tengteng95/Pose-Transfer/blob/f43092613e3d9e9ad1af9f9a0b04a210a82ff97c/tool/generate_pose_map_fashion.py#L30) the image size is set to be (256, 176) where in my downloaded dataset all the images are square (256 * 256). Do I need to center-crop the images in my dataset to 256 * 176 or should I just carry on training and ignore the inconsistency? Looking forward to hearing from you!

**Comment by tengteng95** [comment]
Yes, we crop the image in a center-crop fashion.

**Comment by Lotayou** [comment]
Okay, thanks to know:)
