### ISSUE TITLE
Trained Model for your network

### ISSUE THREAD

**Issue by MendelXu** [tengteng95/Pose-Transfer#2]
Nice work. Could you provide a trained model for your network? I only found the pretrained model for pose estimation in the google drive.
Thanks.:smile:

**Comment by MendelXu** [comment]
Ok, I find it. 👍 Maybe you should place it in a special folder instead of the dataset folder.

**Comment by tengteng95** [comment]
Thanks. You can download our trained model **latest_net_netG.pth** under the folder Pose-Transfer/DeepFashion/ and Pose-Transfer/DeepFashion/Market1501  for these two datasets respectively from google drive.

**Comment by tengteng95** [comment]
Thanks. You can download our trained model **latest_net_netG.pth** under the folder Pose-Transfer/DeepFashion/ and Pose-Transfer/DeepFashion/Market1501  for these two datasets respectively from google drive.

**Comment by MendelXu** [comment]
> Thanks. You can download our trained model **latest_net_netG.pth** under the folder Pose-Transfer/DeepFashion/ and Pose-Transfer/DeepFashion/Market1501 for these two datasets respectively from google drive.
Duplicate response.:cry:
