### ISSUE TITLE
How do you split datasets to get 'train.lst' and 'test.lst'

### ISSUE THREAD

**Issue by TwistSun** [tengteng95/Pose-Transfer#22]
Thanks for your interesting work! How do you split the full fashion dataset into trainset and testset? I see the 'train.lst' and 'test.lst', but i want to know how to get these two 'lsts'. Randomly select in the whole sets or select test images with fixed number for each personID?

**Comment by tengteng95** [comment]
Hi! The dataset split files are generated by the following steps:
1. First, we remove the images with no human body detected by checking the keypoint files.
2. Then, we include all the pairs of (imgA, imgB) from each personID into the dataset. 

We use the code from [Deformable](https://github.com/AliaksandrSiarohin/pose-gan/blob/master/create_pairs_dataset.py) to generate the dataset splits. You can refer it for details.

**Comment by TwistSun** [comment]
Got it. Thank you!

**Comment by sparshgarg23** [comment]
@tengteng95  few follow up questions.
the script create_pairs_dataset.py is used to generate the .csv files .Could you tell me what are the next steps to generate the .lst files.
I am trying to use the model on my own dataset.But first  i would like to understand what preprocessing steps need to be taken before I can begin the training.
