### ISSUE TITLE
no path separator ‘/’ of image paths in train.lst and test.lst

### ISSUE THREAD

**Issue by SkyeLu** [tengteng95/Pose-Transfer#24]
Hi, thanks for your interesting work! I found that there is no path separator ‘/’ of image paths in train.lst and test.lst, so when I run generate_fashion_datasets.py, I got following message:

`cp: cannot stat 'fashion_data/DeepFashion/fashionWOMENTees_Tanksid0000290606_2side.jpg': No such file or directory
cp: cannot stat 'fashion_data/DeepFashion/fashionWOMENPantsid0000687301_1front.jpg': No such file or directory
`
......
How can I fix this? Thanks a lot!

**Comment by ah651** [comment]
Have you fix this problem? I met this problem too.

**Comment by tengteng95** [comment]
Hi! You can transfer the raw path (e.g. fashion/MEN/Shorts/id_00003412/01_4_full.jpg) to the format shown in .lst files (e.g. fashionMENShortsid0000341201_6flat.jpg) as following:

```
# path_names: fashion/MEN/Shorts/id_00003412/01_4_full.jpg -> fashionMENShortsid0000341201_6flat.jpg
 path_names = a.split('/') 
 path_names[2] = path_names[2].replace('_', '')
 path_names[3] = path_names[3].replace('_', '')
 path_names[4] = path_names[4].split('_')[0] + "_" + "".join(path_names[4].split('_')[1:])
 path_names = "".join(path_names)
```

**Comment by SkyeLu** [comment]
Hi, thanks for your reply! But the problem we met is how to transfer the format shown in .lst files to the raw path(e.g. fashionMENShortsid0000341201_6flat.jpg  ->  fashion/MEN/Shorts/id_00003412/01_4_full.jpg). Because the file path in the format shown in .lst can not be found by the system('No such file or directory').

**Comment by Checkmate986212** [comment]
Hi, I found the same problem as @SkyeLu said. How to fix it? @tengteng95  Thanks!

**Comment by tengteng95** [comment]
Hi, you can copy the raw images and rename them following the code above.

**Comment by Checkmate986212** [comment]
Alright. Thanks!

**Comment by Ha0Tang** [comment]
@tengteng95 Why `fashion/MEN/Shorts/id_00003412/01_4_full.jpg` changed to  `fashionMENShortsid0000341201_6flat.jpg` rather than `fashionMENShortsid0000341201_4full.jpg`, is this a typo?

**Comment by SkyeLu** [comment]
Hi, actually I use the code blow to rename and move image files.

`import os  
import shutil  

IMG_EXTENSIONS = [  
    '.jpg', '.JPG', '.jpeg', '.JPEG',  
    '.png', '.PNG', '.ppm', '.PPM', '.bmp', '.BMP',  
]  


def is_image_file(filename):  
    return any(filename.endswith(extension) for extension in IMG_EXTENSIONS)  

def make_dataset(dir):  
    images = []  
    assert os.path.isdir(dir), '%s is not a valid directory' % dir  
    new_root = 'DeepFashion'  
    if not os.path.exists(new_root):  
        os.mkdir(new_root)  

    for root, _, fnames in sorted(os.walk(dir)):  
        for fname in fnames:  
            if is_image_file(fname):  
                path = os.path.join(root, fname)  
                path_names = path.split('/')   
                #path_names[2] = path_names[2].replace('_', '')  
                path_names[3] = path_names[3].replace('_', '')  
                path_names[4] = path_names[4].split('_')[0] + "_" + "".join(path_names[4].split('_')[1:])  
                path_names = "".join(path_names)  
                new_path = os.path.join(root, path_names)  
                os.rename(path, new_path)  
                shutil.move(new_path, os.path.join(new_root, path_names))  

make_dataset('fashion')`

**Comment by SkyeLu** [comment]
Hi, actually I use the code blow to rename and move image files.

`import os  
import shutil  

IMG_EXTENSIONS = [  
    '.jpg', '.JPG', '.jpeg', '.JPEG',  
    '.png', '.PNG', '.ppm', '.PPM', '.bmp', '.BMP',  
]  

def is_image_file(filename):  
    return any(filename.endswith(extension) for extension in IMG_EXTENSIONS)  

def make_dataset(dir):  
    images = []  
    assert os.path.isdir(dir), '%s is not a valid directory' % dir  
    new_root = 'DeepFashion'  
    if not os.path.exists(new_root):  
        os.mkdir(new_root)  

    for root, _, fnames in sorted(os.walk(dir)):  
        for fname in fnames:  
            if is_image_file(fname):  
                path = os.path.join(root, fname)  
                path_names = path.split('/')   
                #path_names[2] = path_names[2].replace('_', '')  
                path_names[3] = path_names[3].replace('_', '')  
                path_names[4] = path_names[4].split('_')[0] + "_" + "".join(path_names[4].split('_')[1:])  
                path_names = "".join(path_names)  
                new_path = os.path.join(root, path_names)  

                os.rename(path, new_path)  
                shutil.move(new_path, os.path.join(new_root, path_names))  


make_dataset('fashion')`

**Comment by Tianbao372330** [comment]
Hi! Have you fix this problem? I met this problem too. Thanks! @SkyeLu

**Comment by SkyeLu** [comment]
Hi, actually I use following code to fix it(suppose the directory ’fashion' is where you store the downlaod dataset), to run this code, just download the dataset and rename it to 'fashion', the renamed images will be store in the directory 'DeepFashion'.

import os
import shutil

IMG_EXTENSIONS = [
    '.jpg', '.JPG', '.jpeg', '.JPEG',
    '.png', '.PNG', '.ppm', '.PPM', '.bmp', '.BMP',
]


def is_image_file(filename):
    return any(filename.endswith(extension) for extension in IMG_EXTENSIONS)


def make_dataset(dir):
    images = []
    assert os.path.isdir(dir), '%s is not a valid directory' % dir
    new_root = 'DeepFashion'
    if not os.path.exists(new_root):
        os.mkdir(new_root)

    for root, _, fnames in sorted(os.walk(dir)):
        for fname in fnames:
            if is_image_file(fname):
                path = os.path.join(root, fname)
                path_names = path.split('/') 
                #path_names[2] = path_names[2].replace('_', '')
                path_names[3] = path_names[3].replace('_', '')
                path_names[4] = path_names[4].split('_')[0] + "_" + "".join(path_names[4].split('_')[1:])
                path_names = "".join(path_names)
                new_path = os.path.join(root, path_names)

                os.rename(path, new_path)
                shutil.move(new_path, os.path.join(new_root, path_names))

make_dataset('fashion')

**Comment by wangzheliu** [comment]
> Hi, thanks for your interesting work! I found that there is no path separator ‘/’ of image paths in train.lst and test.lst, so when I run generate_fashion_datasets.py, I got following message:
> 
> `cp: cannot stat 'fashion_data/DeepFashion/fashionWOMENTees_Tanksid0000290606_2side.jpg': No such file or directory cp: cannot stat 'fashion_data/DeepFashion/fashionWOMENPantsid0000687301_1front.jpg': No such file or directory `
> ......
> Do you fix this problem?

**Comment by tengteng95** [comment]
@wangzheliu  Hi, I have updated **generate_fashion_datasets.py** and the ReadMe file. Hope it would be helpful.
