### ISSUE TITLE
about pretrained model performance and deformable skip

### ISSUE THREAD

**Issue by wencaizhong** [tengteng95/Pose-Transfer#27]
Hi, I tested the provided pretrained generator on Market1501, but I got poor scores (SSIM: 0.281 IS:  3.16) which is not consistent with the paper. The version of Pytorch I used is 0.4.  I also tested the model trained by myself, the perfomance is much better.

Anather question is about the deformaable skip, I am confused about how to combile PATN with deformable gans, could you give more details about what the skip connections connect?
Thanks.

**Comment by tengteng95** [comment]
Hi,  we test our model on both Pytorch0.3.1 and Pytorch1.0.1,  and the results are consistent. At the moment, I have no idea why there is a performance gap in your case. I will test our model on Pytorch0.4 later.

We add deformable skip edge between the encoder and the decoder by combining the feature maps in the same resolution. I have a lot of things to do recently. I'll upload the codes for this part when I am free.

**Comment by jessemelpolio** [comment]
The codes of integration of deformable skip connection and our network are currently released. Please see the PATN_Fine branch for more details.

**Comment by wencaizhong** [comment]
Thanks for your reply!
