### ISSUE TITLE
training with my data

### ISSUE THREAD

**Issue by JingJLiu** [tengteng95/Pose-Transfer#29]
Hello, I trained with my own data. During the test, I found that if the movements of the source image and the target image were too different, the generated person's arms (between shoulder and elbow) were always broken. May I ask if you have this kind of problem?

**Comment by jessemelpolio** [comment]
It would be nice if you could provide some samples. If the pose loses the joints near arms, it could be possible. But if the pose is complete, we haven't met such issue yet. Again, if you could provide some examples, we may be able to help you better.

**Comment by JingjingLiu0223** [comment]
Firstly,thank you for your reply.I will give you some example.Like this,the first picture is the source image,the third is the generate image,and the second is the label.We can see,the arm is broken,and I find most pose transfer both have this problem.Do you have any suggestion to solve this problem?Thank you again.







------------------ Original ------------------

**Comment by jessemelpolio** [comment]
Since we've discussed about this problem through email, I'm gonna close this issue.
