### ISSUE TITLE
How to obatin keypoint annotation?

### ISSUE THREAD

**Issue by jinningli** [tengteng95/Pose-Transfer#3]
Hello, this is really a wonderful project. I have some questions when reproducing the project:
1. Did you generate `market-pairs-train.csv, market-pairs-test.csv, market-annotation-train.csv, market-annotation-train.csv` using this model: `https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation` ? 
2. What are the meanings of the 18 keypoints? (which is the eye, which is the shoulder, etc)
3. Can I build my own dataset using the Realtime_Multi-Person_Pose_Estimation model?

Thank you!

**Comment by tengteng95** [comment]
Thanks!
1. Yes, for **annotation** files, we use the OpenPose model as the link above, which is also adopted in previous works [Deform](https://github.com/AliaksandrSiarohin/pose-gan).  For **pairs** files (dataset split), we use the code from [Deform](https://github.com/AliaksandrSiarohin/pose-gan).
2. You can find the meanings of the 18 keypoints in the 23rd line in the file Pose-Transfer/tool/pose_utils.py.
3. Yes.
