### ISSUE TITLE
where are fasion-annotation-test.csv',fasion-annotation-train.csv?

### ISSUE THREAD

**Issue by wangzheliu** [tengteng95/Pose-Transfer#33]
in resize_fashion.py，line46,
resize_annotations(root_dir + 'fasion-annotation-test.csv', root_dir + 'fasion-resize-annotation-test.csv')

resize_dataset(root_dir + '/train', root_dir + 'fashion_resize/train')
resize_annotations(root_dir + 'fasion-annotation-train.csv', root_dir + 'fasion-resize-annotation-train.csv')
Ijust find  fasion-resize-pairs-train.csv, fasion-resize-pairs-test.csv

**Comment by busekuz** [comment]
It was metioned at README.md as below,

- Download train/test pairs and train/test key points annotations from [Google Drive ](https://drive.google.com/open?id=1YMsYXc41dR3k8YroXeWGh9zweNUQmZBw) or [Baidu Disk](https://pan.baidu.com/s/1fcMwXTUk9XKPLpaJSodTrg), including fasion-resize-pairs-train.csv, fasion-resize-pairs-test.csv, fasion-resize-annotation-train.csv, fasion-resize-annotation-train.csv. Put these four files under the fashion_data directory.

**Comment by jiyooonp** [comment]
Hello, I am not able to get the fasion-annotation-test.csv from anywhere. Could you point me to the right download path?
