### ISSUE TITLE
ResnetDiscriminator downsampling number 

### ISSUE THREAD

**Issue by busekuz** [tengteng95/Pose-Transfer#34]
Hello!
I have a question about ResnetDiscriminator's downsampling process.

As far as I see n_downsampling is either smaller or equal to 2 or it is 3 (there is no conv_layers for n_downsampling > 3).
My question is, is there an intuition behind it or did you limited the number of downsampling according to the results or something else?

**Comment by tengteng95** [comment]
Hi, GAN is a  game between the generator and the discriminator. A too strong discriminator will dominate the game, and thus leads to difficulties in the optimizing process of the generator. Hence, we usually set n_downsampling as a small value, such as 2 and 3, which can reduce the capacity of the discriminator. Besides, in our experience, it leads to more stable training process and better results.
