### ISSUE TITLE
No model details in ‘pose_estimator.h5’

### ISSUE THREAD

**Issue by ztjryg4** [tengteng95/Pose-Transfer#36]
Hi, I tried to run 'compute_coordinates.py' to generate keypoints files for the DukeMTMC-reID dataset. But there is a warning "No training configuration found in save file", and keypoint data in the csv file are all -1.
I will be so appreciate if you could help me with the problem :-)

**Comment by SihYingChen** [comment]
Hi, I wanna generate keypoints files for my own dataset. But I also have same problem that csv file are all -1.
Have you solved it? Could you help me to figure it out? Thanks a lot.

**Comment by ztjryg4** [comment]
> Hi, I wanna generate keypoints files for my own dataset. But I also have same problem that csv file are all -1.
> Have you solved it? Could you help me to figure it out? Thanks a lot.

I carefully checked my csv file and found that, although there are a lot of -1, there are still many valid values.
I guess the reason for this phenomenon is that the model failed to capture the keypoints of a part of the image.

**Comment by SihYingChen** [comment]
> I carefully checked my csv file and found that, although there are a lot of -1, there are still many valid values.
> I guess the reason for this phenomenon is that the model failed to capture the keypoints of a part of the image.

Thank you for the prompt reply. 
I just checked my csv file and i make sure that there are all -1 in csv file.
And, I also have some warning message "warn("Anti-aliasing will be enabled by default in skimage 0.15 to ", but I think they are not related to each other.
Actually I feel the same way. Did you choose the other model to get better result of keypoints?
Now, I want to run the test by my own images. Had you run it successfully before?

**Comment by ztjryg4** [comment]
> > I carefully checked my csv file and found that, although there are a lot of -1, there are still many valid values.
> > I guess the reason for this phenomenon is that the model failed to capture the keypoints of a part of the image.
> 
> Thank you for the prompt reply.
> I just checked my csv file and i make sure that there are all -1 in csv file.
> And, I also have some warning message "warn("Anti-aliasing will be enabled by default in skimage 0.15 to ", but I think they are not related to each other.
> Actually I feel the same way. Did you choose the other model to get better result of keypoints?
> Now, I want to run the test by my own images. Had you run it successfully before?

Sorry, I have not tried other models to estimate the pose.
I successfully ran it on the DukeMTMC-ReID dataset, although the key points of many images were not successfully captured (perhaps because the image quality is not good enough, I am not sure).

**Comment by CodeAunt** [comment]
> > I carefully checked my csv file and found that, although there are a lot of -1, there are still many valid values.
> > I guess the reason for this phenomenon is that the model failed to capture the keypoints of a part of the image.
> 
> Thank you for the prompt reply. I just checked my csv file and i make sure that there are all -1 in csv file. And, I also have some warning message "warn("Anti-aliasing will be enabled by default in skimage 0.15 to ", but I think they are not related to each other. Actually I feel the same way. Did you choose the other model to get better result of keypoints? Now, I want to run the test by my own images. Had you run it successfully before?

Hi, have you managed to fix this? I got the same problem that all my annotations generated are -1.
