### ISSUE TITLE
Which version of OpenPose do you  use?

### ISSUE THREAD

**Issue by jszgz** [tengteng95/Pose-Transfer#37]
Can you give a link? I've found two keras implementation.
[michalfaber/keras_Realtime_Multi-Person_Pose_Estimation](https://github.com/michalfaber/keras_Realtime_Multi-Person_Pose_Estimation)
[anatolix/keras_Realtime_Multi-Person_Pose_Estimation](https://github.com/anatolix/keras_Realtime_Multi-Person_Pose_Estimation)

**Comment by tengteng95** [comment]
Hi, as mentioned in our ReadMe, we use the [official version](https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation) .
