### ISSUE TITLE
Could you please publish the results of *ablation studies* in your paper?

### ISSUE THREAD

**Issue by mtroym** [tengteng95/Pose-Transfer#38]
As menstioned in your fancy oral paper.
- PG2
- VUNet
- DeformGan
With *correspondance* to your code's data split.
After all, Thanks!

**Comment by MTonyM** [comment]
![image](https://user-images.githubusercontent.com/30402475/65581287-c50fe400-dfad-11e9-81d8-1e9d34beeab4.png)

**Comment by jessemelpolio** [comment]
I guess you're mentioning the qualitative results of PG2, VUNet and Deform. You could refer to [testing code](https://github.com/CVPR19-anonymous/pose_transfer_test_code) to have more details. The data split is already given in the ReadMe.
<img width="939" alt="image" src="https://user-images.githubusercontent.com/5879276/65602096-e258a880-dfd5-11e9-9673-4803fb671a62.png">

We can clear up these results in the future as we are currently busy. So you could refer to the code at first. I hope this could help you somehow.

**Comment by mtroym** [comment]
Thanks!
