### ISSUE TITLE
docker image for Evaluation

### ISSUE THREAD

**Issue by budui** [tengteng95/Pose-Transfer#4]
I have tried&failed 3000 times to do `evaluation`. 
Finally I came to a conclusion: docker, docker, we need docker!

Share my solution below:
```bash
docker run -v <Pose-Transfer path>:/tmp -w /tmp --runtime=nvidia -it --rm tensorflow/tensorflow:1.4.1-gpu-py3 bash
# now in docker:
$ pip install scikit-image tqdm 
$ python tool/getMetrics_market.py
```

**Comment by tengteng95** [comment]
Great thanks to you! This can be helpful for others who meet the same problem. I will update the README file to include this great solution.

**Comment by 2110317008** [comment]
> Great thanks to you! This can be helpful for others who meet the same problem. I will update the README file to include this great solution.

root@833c2b940c92:/home/Pose-Transfer-master/Pose-Transfer# CUDA_VISIBLE_DEVICES=0 python tool/getMetrics_market.py
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "tool/getMetrics_market.py", line 2, in <module>
    from inception_score import get_inception_score
  File "/home/Pose-Transfer-master/Pose-Transfer/tool/inception_score.py", line 12, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 54, in <module>
    from tensorflow.python.platform import app
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 23, in <module>
    from absl.app import run as _run
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 35, in <module>
    import pdb
  File "/usr/lib/python3.6/pdb.py", line 136, in <module>
    class Pdb(bdb.Bdb, cmd.Cmd):
AttributeError: module 'cmd' has no attribute 'Cmd'
root@833c2b940c92:/home/Pose-Transfer-master/Pose-Transfer# 

When I evaluate, this error occurred. What should I do?
Thank you!

**Comment by BJTUJia** [comment]
I encounter the same error. Have you found a solution yet?

**Comment by busekuz** [comment]
At first, I have also encountered AttributeError: module 'cmd' has no attribute 'Cmd' error.
 
I solved this problem by,

-  changing tool/cmd.py file's name to something different than cmd such as cmd_1.py

- also changing the import statement in compute_cordinates.py accordingly (ex.: from cmd_1 import args)

You can check this [answer](https://stackoverflow.com/a/22601322/10152698) if you want to.

**Comment by Ha0Tang** [comment]
Install `pip install tensorflow==1.4.0` works for me.
