### ISSUE TITLE
How to visualize the attention maps?

### ISSUE THREAD

**Issue by luowy1001** [tengteng95/Pose-Transfer#44]
Thx for your great work!
I want to know how to visualize the attention maps? Where are the relevant codes?
@tengteng95

**Comment by mtroym** [comment]
@luowy1001 the attention maps can use hookers or intermediate results to re-produce. The pytorch1.3.0 has a new feature. I hope you will figure it out.

**Comment by luowy1001** [comment]
Thanks for your reply!
I think it is simple to get attention features. However, what I want to know is how to make a multi-channel features map to a 3-channels image for visualization.
@mtroym

**Comment by luowy1001** [comment]
I guess that the attention map is averaged along the channel dimension, so it is compressed to a one-channel image?

**Comment by mtroym** [comment]
@luowy1001 Hi, You can use magnitude to calculate the heatmaps or other mapping functions. Hope it helps you.
