### ISSUE TITLE
doubt about the equation(5) in original paper

### ISSUE THREAD

**Issue by venuszhou** [tengteng95/Pose-Transfer#45]
@tengteng95 hi, Could you please help me with the quation(5)  in your original paper? I don't exactly know what the **Pt** is and how you can get it. Thanks.

**Comment by jessemelpolio** [comment]
Pt means the target image. You could simply take it as the ground truth image.

**Comment by venuszhou** [comment]
@jessemelpolio thanks, but how can you get the target (pose) image? What the author does is to try to utilize the model to generate the image with target pose, but how can you get the ground truth? Please point it out if I made any misunderstanding.

**Comment by jessemelpolio** [comment]
Eq. 5 is used in the training procedure. It doesn't necessarily mean to have this target image in the testing phase.
