### ISSUE TITLE
running_mean and running_var how to remove by code?

### ISSUE THREAD

**Issue by Gavin-Evans** [tengteng95/Pose-Transfer#47]
Hello,
When I use the pre-training model, I get the following error, what should I do?
Error:
`RuntimeError: Error(s) in loading state_dict for PATNetwork:
	Unexpected running stats buffer(s) "model.stream1_down.2.running_mean" and "model.stream1_down.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.stream1_down.5.running_mean" and "model.stream1_down.5.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.stream1_down.8.running_mean" and "model.stream1_down.8.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.stream2_down.2.running_mean" and "model.stream2_down.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.stream2_down.5.running_mean" and "model.stream2_down.5.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.stream2_down.8.running_mean" and "model.stream2_down.8.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.att.0.conv_block_stream1.2.running_mean" and "model.att.0.conv_block_stream1.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.att.0.conv_block_stream1.7.running_mean" and "model.att.0.conv_block_stream1.7.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
`
and rm_insnorm_running_vars.py couldn't find in tool's file,
thank you

**Comment by jessemelpolio** [comment]
Please look at the [notes](https://github.com/tengteng95/Pose-Transfer#notes)

**Comment by Gavin-Evans** [comment]
rm_insnorm_running_vars.py couldn't be found in tool's file,   where's it? 
I use pytorch 1.0 ,when only tested on the DeepFashion's pre-training model, it will report the above error

**Comment by abhisheksrivastava2397** [comment]
yes the rm_insnorm_running_vars.py script is not in the repository.
where is it?
what is the alternative

**Comment by jessemelpolio** [comment]
Check out the branch pytorch_1.0. The script is inside the tool folder.

**Comment by tengteng95** [comment]
Hi,  in the branch pytorch_v1.0, we provide the script for this. Please refer to [Here](https://github.com/tengteng95/Pose-Transfer/blob/pytorch_v1.0/tool/rm_insnorm_running_vars.py).
