### ISSUE TITLE
how to use the generated data？

### ISSUE THREAD

**Issue by Gary-Deeplearning** [tengteng95/Pose-Transfer#5]
Hi. How can I use the generated data by the pose-transfer model to expand the reid training set? However, I found that there was a clear difference between the target and the original, that is the object ID had been changed.

**Comment by tengteng95** [comment]
1. Generate an image pair list, that is a ".csv" file. For each person ID, you can randomly sample target poses from the whole dataset.
2. Use the well-trained model to generate images. 
3. Train a re-ID model with the generated images and reduced (or full) real training dataset. 

Please refer to Section5 in our paper for more details.

**Comment by Gary-Deeplearning** [comment]
yep, thanks for your reply, I will finish the experiment according to the points you mentioned.
