### ISSUE TITLE
IndexError: list index out of range When I run getMetrics_market.py

### ISSUE THREAD

**Issue by studabyd** [tengteng95/Pose-Transfer#58]
I don't no why It showed the following error.
![2019-12-17 12-09-49屏幕截图](https://user-images.githubusercontent.com/52878967/70964328-6480d680-20c6-11ea-808d-a626a6c91f61.png)
![2019-12-17 12-10-05屏幕截图](https://user-images.githubusercontent.com/52878967/70964331-677bc700-20c6-11ea-9ea8-14d497627330.png)

**Comment by tengteng95** [comment]
Hi, please make sure you set the path variable **generated_images_dir** correctly in the file getMetrics_market.py.

**Comment by studabyd** [comment]
Thanks, I found that the path is wrong and I had solved this question with your advice.
