### ISSUE TITLE
 How to run the code with two GPU servers?

### ISSUE THREAD

**Issue by wangpeiyan320** [tengteng95/Pose-Transfer#73]
Could you please tell me if your code can run with two GPU servers? If so, can you tell me how to modify it? 
And I followed the instruction indicated by the link:
https://blog.csdn.net/alxe_made/article/details/80471739
but it didn't work out.
Your understanding and clarification will be highly appreciated. Thank you.

**Comment by tengteng95** [comment]
Hi，you can train the model with multiple GPUs by simply modifying the **--gpu** options in the training script. For example, training the model on the first two GPUs of your server, you can train the model with -**-gpu 0,1**.
