### ISSUE TITLE
runtime erroe

### ISSUE THREAD

**Issue by stdntlfe** [tengteng95/Pose-Transfer#83]
<pre>Total number of parameters: 41358019
-----------------------------------------------
model [TransferModel] was created
200
8670
False
 process 0/999999 img ..
/home/arvind/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1332: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn(&quot;nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.&quot;)
Traceback (most recent call last):
  File &quot;test.py&quot;, line 39, in &lt;module&gt;
    model.test()
  File &quot;/home/arvind/dewwork/models/PATN.py&quot;, line 137, in test
    self.fake_p2 = self.netG(G_input)
  File &quot;/home/arvind/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py&quot;, line 489, in __call__
    result = self.forward(*input, **kwargs)
  File &quot;/home/arvind/dewwork/models/model_variants.py&quot;, line 167, in forward
    return self.model(input)
  File &quot;/home/arvind/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py&quot;, line 489, in __call__
    result = self.forward(*input, **kwargs)
  File &quot;/home/arvind/dewwork/models/model_variants.py&quot;, line 148, in forward
    x1, x2, _ = model(x1, x2)
  File &quot;/home/arvind/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py&quot;, line 489, in __call__
    result = self.forward(*input, **kwargs)
  File &quot;/home/arvind/dewwork/models/model_variants.py&quot;, line 63, in forward
    x1_out = x1_out * att
RuntimeError: The size of tensor a (64) must match the size of tensor b (44) at non-singleton dimension 3
</pre>

 please find out the error

**Comment by jessemelpolio** [comment]
I think the input condition image and the poses are not consistently aligned. It seems the width of the condition image/pose heat map is 256 while the width of the pose heat maps/condition image is 176. Please have a check.
