### ISSUE TITLE
Problem loading the model for test.

### ISSUE THREAD

**Issue by akhil451** [tengteng95/Pose-Transfer#85]
Hi, 
I am using the pytorch_v1.0 branch and getting the below error. I have deleted the running_mean keys using the rm_isnorm_runningvars.py file, but am getting the below error.

RuntimeError: Error(s) in loading state_dict for PATNetwork:	Missing key(s) in state_dict: "model.att.0.conv_block_stream1.5.weight", "model.att.0.conv_block_stream1.5.bias", "model.att.0.conv_block_stream2.5.weight", "model.att.0.conv_block_stream2.5.bias", "model.att.1.conv_block_stream1.5.weight", "model.att.1.conv_block_stream1.5.bias", "model.att.1.conv_block_stream2.5.weight", "model.att.1.conv_block_stream2.5.bias", "model.att.2.conv_block_stream1.5.weight", "model.att.2.conv_block_stream1.5.bias", "model.att.2.conv_block_stream2.5.weight", "model.att.2.conv_block_stream2.5.bias", "model.att.3.conv_block_stream1.5.weight", "model.att.3.conv_block_stream1.5.bias", "model.att.3.conv_block_stream2.5.weight", "model.att.3.conv_block_stream2.5.bias", "model.att.4.conv_block_stream1.5.weight", "model.att.4.conv_block_stream1.5.bias", "model.att.4.conv_block_stream2.5.weight", "model.att.4.conv_block_stream2.5.bias", "model.att.5.conv_block_stream1.5.weight", "model.att.5.conv_block_stream1.5.bias", "model.att.5.conv_block_stream2.5.weight", "model.att.5.conv_block_stream2.5.bias", "model.att.6.conv_block_stream1.5.weight", "model.att.6.conv_block_stream1.5.bias", "model.att.6.conv_block_stream2.5.weight", "model.att.6.conv_block_stream2.5.bias", "model.att.7.conv_block_stream1.5.weight", "model.att.7.conv_block_stream1.5.bias", "model.att.7.conv_block_stream2.5.weight", "model.att.7.conv_block_stream2.5.bias", "model.att.8.conv_block_stream1.5.weight", "model.att.8.conv_block_stream1.5.bias", "model.att.8.conv_block_stream2.5.weig...	Unexpected key(s) in state_dict: "model.att.0.conv_block_stream1.6.weight", "model.att.0.conv_block_stream1.6.bias", "model.att.0.conv_block_stream2.6.weight", "model.att.0.conv_block_stream2.6.bias", "model.att.1.conv_block_stream1.6.weight", "model.att.1.conv_block_stream1.6.bias", "model.att.1.conv_block_stream2.6.weight", "model.att.1.conv_block_stream2.6.bias", "model.att.2.conv_block_stream1.6.weight", "model.att.2.conv_block_stream1.6.bias", "model.att.2.conv_block_stream2.6.weight", "model.att.2.conv_block_stream2.6.bias", "model.att.3.conv_block_stream1.6.weight", "model.att.3.conv_block_stream1.6.bias", "model.att.3.conv_block_stream2.6.weight", "model.att.3.conv_block_stream2.6.bias", "model.att.4.conv_block_stream1.6.weight", "model.att.4.conv_block_stream1.6.bias", "model.att.4.conv_block_stream2.6.weight", "model.att.4.conv_block_stream2.6.bias", "model.att.5.conv_block_stream1.6.weight", "model.att.5.conv_block_stream1.6.bias", "model.att.5.conv_block_stream2.6.weight", "model.att.5.conv_block_stream2.6.bias", "model.att.6.conv_block_stream1.6.weight", "model.att.6.conv_block_stream1.6.bias", "model.att.6.conv_block_stream2.6.weight", "model.att.6.conv_block_stream2.6.bias", "model.att.7.conv_block_stream1.6.weight", "model.att.7.conv_block_stream1.6.bias", "model.att.7.conv_block_stream2.6.weight", "model.att.7.conv_block_stream2.6.bias", "model.att.8.conv_block_stream1.6.weight", "model.att.8.conv_block_stream1.6.bias", "model.att.8.conv_block_stream2.6.w...

**Comment by akhil451** [comment]
Is there any step that I am missing?

**Comment by Zhongping-Zhang** [comment]
I meet the same issue, did you solve it?
