### ISSUE TITLE
PATN_fine

### ISSUE THREAD

**Issue by heyuling1019** [tengteng95/Pose-Transfer#88]
Thank you for your great code and the project is very interesting. I couldn't find pre-trained model of PATN_Fine.

 Could you provide it？thankyou！

**Comment by jessemelpolio** [comment]
Hi @heyuling1019 , the pre-trained model for PATN_Fine is now at [this link](https://drive.google.com/drive/folders/1d1GdjnityUZKSSwf_bhcJ2Lc-qsB2w2Y?usp=sharing)  (for pytorch 0.3.1, branch PATN_Fine). Later, I'll change the README file to mention this update.

**Comment by heyuling1019** [comment]
Thank you !







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tengteng95/Pose-Transfer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 中午1:27
收件人:&nbsp;"tengteng95/Pose-Transfer"<Pose-Transfer@noreply.github.com&gt;;
抄送:&nbsp;"HEYULING"<1163672208@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tengteng95/Pose-Transfer] PATN_fine (#88)





 
Hi @heyuling1019 , the pre-trained model for PATN_Fine is now at this link  (for pytorch 0.3.1, branch PATN_Fine). Later, I'll change the README file to mention this update.
