### ISSUE TITLE
About query operation in the code.

### ISSUE THREAD

**Issue by Hoodythree** [tengteng95/Pose-Transfer#89]
Amazing work!But I have a question about the query operation here:
https://github.com/tengteng95/Pose-Transfer/blob/a6bd385ebbf9e4e4c2345b4045573de1f82c8fc9/models/PATN.py#L211
Why we need query the concatenated images?What's the purpose here?
Thank in advance.

**Comment by jessemelpolio** [comment]
Hi, it is a feature directly inherited from the [pytorch_cyclegan_pix2pix repo](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix). It is assumed that all images generated by the generator should be treated as fake images when training the discriminator. However, the current training batch for discriminator doesn't have previous knowledge and the discriminator may forget how previous fake images look like. In this way, sampling the training batch from a "buffer" of previously generated fake images may help improve the training performance of the discriminator. 

If you're interested, you should find Sec. 2.3 of [this paper](https://arxiv.org/pdf/1612.07828v1.pdf) very useful

**Comment by Hoodythree** [comment]
Thank you, I'll check it. Other questions about the translation from cordinates to heatmap: 
```
def cords_to_map(cords, img_size, sigma=6):
    result = np.zeros(img_size + cords.shape[0:1], dtype='uint8')
    for i, point in enumerate(cords):
        if point[0] == MISSING_VALUE or point[1] == MISSING_VALUE:
            continue
        xx, yy = np.meshgrid(np.arange(img_size[1]), np.arange(img_size[0]))
        result[..., i] = np.exp(-((yy - point[0]) ** 2 + (xx - point[1]) ** 2) / (2 * sigma ** 2))
        # result[..., i] = np.where(((yy - point[0]) ** 2 + (xx - point[1]) ** 2) < (sigma ** 2), 1, 0)
    return result
```
- Where the translation strategy comes from, or why did you do like this?
- As you say you filtered out images where no human body is detected, but is there any problem for the generation when the target bone only has few keypoints, say 1 or 2?

Thanks for your patience again.

**Comment by jessemelpolio** [comment]
1) It is derived from the code of [this repo](https://github.com/AliaksandrSiarohin/pose-gan). You can also check their paper for specific reasons (Sec. 3).
2) This is also a strategy adopted from previous works, which we think is quite reasonable. If the target bones only have 1 or 2 keypoints, the target pose could rarely be regarded as human. Our work is mainly centered on integrated human generation rather than generating plausible results from only a few points.
