### ISSUE TITLE
How to train a model with my own dateset？ 

### ISSUE THREAD

**Issue by weilan2018** [tengteng95/Pose-Transfer#9]
I have some person photos and corresponding key points photos, but how can I get them and their pairs in .csv files for successful training?

**Comment by jessemelpolio** [comment]
Refer to the [Data preparation](https://github.com/tengteng95/Pose-Transfer#data-preperation) section in the README. This section exhibits the generation process of the keypoints annotations.

**Comment by tengteng95** [comment]
Hi, I have uploaded an example for generating the training/testing pairs (.csv files).
You can change the path of annotations_file_train(test) & pairs_file_train(test) tool/create_pairs_dataset.py. And then run
`python2 tool/create_pairs_dataset.py`

**Comment by confifu** [comment]
python2 is not supported by numpy and many other packages. Can you please move the code to python2 or maybe suggest how to create pose keypoints with python3?
