### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by sareyu0753** [tengteng95/Pose-Transfer#95]
Hi, your work is exciting.
However, when i use the pretrained model you provided, it seems that the result is not as good as yours. I'm wondering what i've done wrong. I'm testing it with pytorch1.6. Or should i  train the pretrained model deeper?

**Comment by jessemelpolio** [comment]
Pytorch 1.6 branch may still have some issues. As we currently don't have time to check it, you are recommended to use the main branch.

**Comment by sareyu0753** [comment]
Thanks! I'd try the main branch first!
